maidsafe/parsec

src/parsec.rs

In update_round_hashes, we can't expect for the meta-votes to always be
set as the function: set_meta_votes can sometimes fail to set them (for
instance before any observation happen)

fix/parsec: don't expect meta-votes to be set

---

src/dump_network.rs

The meta_votes contain the votes for the faulty nodes as well.
Meanwhile the inital_events only contains the good nodes.
So instead of expecting the length of these two to be the same,
we shall allow the meta_votes contains more entries.

fix/dump_network: meta_votes contains fault node

---

tests/integration_tests.rs

In its current state, our code passes this test. Enable it so we can
catch any regression while investigating the other tests.

fix/parsec: enable minimal_network

---

src/dump_network.rs
src/parsec.rs

Once a block with a given payload already reached consensus, never
consider this payload again as a candidate for consensus.

MAID-2864: fix/parsec: consensused payloads are uninteresting

---

src/meta_vote.rs
src/parsec.rs

When update meta_votes of a peer due to received new events, the
new updated meta_votes shall be taken into account as well.

fix/parsec.git: update all meta_votes

---

src/parsec.rs

Inside the stop_wait function call, along the events created by
itself, check the meta_vote of the peer in the waiting.

fix/parsec: check meta_vote of peer in stop_wait

---

src/dump_graph.rs
src/gossip/event.rs
src/parsec.rs
tests/integration_tests.rs
tests/utils/network.rs
tests/utils/peer.rs

The valid blocks carried don't get recalculated on old gossip events
when clearing the consensus data, which causes consensus to occur later
and later as old events aren't ever again considered as interesting
events.

MAID-2864: fix/parsec: fix receeding consensus

---

src/parsec.rs

The previous logic for selecting the right hash to remove was incorrect,
which led to failures as nodes didn't agree on the oldest interesting
event.

MAID-2913: fix/parsec: fix MAID-2913

---

tests/integration_tests.rs

During soak testing, we found that this test exceeded 100 iterations
every few thousand runs.
Relax the max number of iterations slightly to make that failure much
more unlikely and improve tests reliability.

MAID-2919: fix/parsec: allow more iterations for one test

---

README.md
examples/basic.rs
src/dump_graph.rs
tutorial.md

As well as automatically creating SVGs, this also makes the instructions somewhat more Windows-friendly:
* Paths are printed in a way that is more useful for copy-pasting in a Windows console.
* Instructions now avoid use of `*.dot` which fails on Windows.
* Instructions now avoid expectation that Firefox is in the path as this is unusual on Windows.

feat/parsec: try to generate SVG files from dot files

---

tests/integration_tests.rs

This might have been causing heisenbugs when running all tests with a predefined seed... oops.

Fix some tests not using the global seed

---

tests/utils/network.rs
tests/utils/schedule.rs

Even in a correct execution the nodes only come to consensus after an
unknown number of steps. This means we don't know how many steps we need
to generate in order for the test to pass. In order to give the nodes
enough time, we will now generate a lot of steps in advance, but
interrupt the execution as soon as consensus is reached; or, if there is
a bug, if we detect that nodes have disagreeing orders of transactions.

interrupt the test if consensus complete or broken

---

src/meta_vote.rs

This PR replaces `MetaVote`'s `BTreeSet<bool>` with a much lighter enum `BoolSet`.
I have tried to replicate the `BTreeSet` api so the change is as simple as possible.

replace BTreeSet<bool> with a much lighter enum

---

Cargo.toml
src/lib.rs

* Update doc attributes as html_root_url is becoming soft deprecated
* Update unwrap dependency to use newfangled macro

[MAID-2922, MAID-2926] Miscellaneous chores

---

src/parsec.rs

...that is, rename `does_strongly_see` to `strongly_sees` ;)

MAID-2997: extract a strongly_sees method

---

tests/integration_tests.rs
tests/utils/proptest/schedule.rs

Send the Schedule output to a lower log level to avoid hiding the
directory where the graphs go from the output.
Note that the Schedule output is still logged to schedule.txt when
dumping graphs.
MAID-3139

MAID-3139: Send the Schedule output to lower log level

---

dev_utils/src/network.rs
dev_utils/src/peer.rs
examples/basic.rs
src/block.rs
src/gossip/event.rs
src/lib.rs
src/observation.rs
src/parsec.rs
src/vote.rs

This provides visibility of some network events about which Parsec is interested; namely add and remove peer.

MAID-3044: add observation enum

---

.travis.yml

clippy and rustfmt stopped compiling due to an issue with their
proc_macro dependency.
Stop running on nightly for now as we don't have the bandwidth to jump
through so many hoops as work must get done.

chore/ci: Allow failures on nightly for now

---

src/parsec.rs
src/peer_list.rs

This PR adds the `Parsec::from_existing` constructor for nodes that are joining existing sections. It also introduces the concept of inactive peer. Currently there is almost no distinction between active and inactive peers, except that it is not allowed to create gossip for inactive ones. This will change in the future.

MAID-3032: Add constructor for joining existing section

---

src/dot_parser.rs
src/dump_graph.rs
src/gossip/cause.rs
src/gossip/event.rs
src/gossip/mod.rs
src/lib.rs
src/mock.rs
src/vote.rs

Reading a dumped dot file and parse event graph info from it.
This is to be used for re-construct a parsec for testing purpose.

MAID-2970 feat/parsec: parse event graph info from dot file

---

src/dot_parser.rs
src/dump_graph.rs
src/gossip/cause.rs
src/gossip/event.rs
src/gossip/mod.rs
src/mock.rs
src/vote.rs

This reduces almost all of the feature-gated functionality required for dot file reading and writing to just dump_graph.rs, dot_parser.rs and event.rs.

chore/parsec: concentrate dot-handling in event

---

src/dot_parser.rs
src/meta_vote.rs
src/parsec.rs

To help with functional testing, create an extra constructor for Parsec
tagged that can initialise a partial Parsec with a few events from a
gossip graph using the dot_parser.
MAID-2974

MAID-2974: Add constructor initialising Parsec using dot_parser

---

.travis.yml
appveyor.yml

This allows to install rustfmt and clippy on stable with rustup.
Drop nightly as it was mostly needed for rustfmt and clippy.

chore/ci: update scripts to rust stable 1.29.0

---

Cargo.toml
src/gossip/event.rs
src/lib.rs
src/mock.rs

To be able to properly test other components relying on signature
verification, plug in safe_crypto into PeerId by adding a public and
private signing pair. We want to keep the traits inside id.rs as they
are.
MAID-3152

MAID-3152: Use safe_crypto signing key pair

---

tests/integration_tests.rs
tutorial.md

When looking at the output of the test:
test_duplicate_votes_before_gossip, one observes no duplicate vote. This
is because the behaviour of PARSEC is to only vote for a given event
once.
To make this obvious when casually browsing the test output, rename the
test to test_duplicate_vote_is_reduced_to_single.
MAID-3140

MAID-3140: Rename test_duplicate_votes_before_gossip

---

input_graphs/parsec_functional_tests_add_peer/add_fred.dot
input_graphs/parsec_functional_tests_add_peer/naughty_carol.dot
input_graphs/parsec_functional_tests_from_parsed_contents/0.dot
input_graphs/parsec_functional_tests_from_parsed_contents/1.dot
input_graphs/parsec_functional_tests_remove_peer/remove_eric.dot
src/dev_utils/dot_parser.rs
src/gossip/event.rs
src/parsec.rs

This change makes it so that if all peers vote for observations in a particular order, the agreed order will be the same.
This is done by modifying the way interesting events store interesting content. Until now, the order was just lexical. Now, every interesting event stores the content in the order its creator voted for it, and the first payload is chosen as a candidate. This way, if a payload was the first voted for for all peers, it will be chosen as the next consensused one.

Fix the Validity property of consensus

---

src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/schedule.rs
src/meta_vote.rs
src/parsec.rs
src/peer_list.rs

This also improves the testing framework:
* blocks are now being checked for only being signed by valid voters
* error reporting is improved in cases when test is interrupted by broken consensus (can supersede #112)

MAID-3191: Enable handwritten schedules, improve testing framework

---

tests/integration_tests.rs

We experienced the situation that Carol got removed too quick that
before Hank got consensused to be added. Which blocks Add(Hank) to
get consensused.

MAID-3202: avoid remove Carol too quick

---

src/observation.rs
src/parsec.rs

This handles MissingGenesis based on the assumption that we will always get initialised with a genesis group that is a result of consensus of some section - so we will either have the correct genesis group in events carrying `Observation::Genesis`, or in the peer list.
Supersedes #122

MAID-3070: Detect and handle MissingGenesis

---

src/observation.rs
src/parsec.rs

A node creates an event with Observation::Genesis. Their observation is in disagreement with my consensus list (either my Genesis::Observation or the genesis being consensused if I was added after genesis).

MAID-3067: Detect and handle malice: IncorrectGenesis

---

src/error.rs
src/lib.rs
src/parsec.rs

This PR introduces the following changes to malice handling:
1. Malice detection now happens before the event is added to the graph
2. Accusations are raised only after all events from the gossip message has been processed
3. Exception is the `IncorrectGenesis` malice, which raises the accusation immediately and interrupts processing of all the events in the message to prevent populating the graph with potentially large number of invalid events.
There is also a minor refactoring in a separate commit which adds type alias for `Result<T, Error>` to reduce verbosity.

MAID-3210: Change malice handling

---

src/observation.rs
src/parsec.rs
src/peer_list.rs

The detection of invalid accusation is based on the idea that if we encounter an event carrying `Accusation`, we should have already processed the corresponding offending events, so it should be enough to look in our pending accusations or already raised accusation to see whether we have the same accusation. If we don't, their accusation is invalid. This relies heavily on the assumption that accusations are raised immediately after sync events which implies that any accusation is always a descendant of its offending event(s). Unless I'm wrong :grimacing: .

MAID-3052: Impl - detect invalid accusation

---

src/parsec.rs
src/peer_list.rs

- add method to check whether there are any not yet consensused observations in the graph
- add method to retrieve all unpolled observations created by us

MAID-3222 and MAID-3223: Expand the public API to support routing integration

---

src/gossip/event.rs
src/parsec.rs
src/peer_list.rs

This PR attempts to fix an existing issue where a peer added via consensus on `Observation::Add` would not have their membership list properly initialized (see https://maidsafe.atlassian.net/browse/MAID-3214 for more detailed description of why this happens). The fix is to wait for the first sync-event by the new peer and then fetch the creator of the other-parent of that sync-event and use their historic membership list at the time the other-parent was created. To achieve this, we keep track of all the changes to the membership lists so we can reconstruct them at any given point in time.
- Why can we copy the other-parent's creator's membership list? Because the new peer (let's call him Eric) is guaranteed to know all the peers the other-parent's creator (let's call him Dave) knew at the …

MAID-3214: initialise new peer membership list

---

src/dev_utils/dot_parser.rs
src/dump_graph.rs
src/gossip/event.rs
src/meta_voting/meta_elections.rs
src/meta_voting/meta_event.rs
src/meta_voting/meta_vote.rs
src/meta_voting/mod.rs
src/parsec.rs
src/peer_list.rs

This PR takes all data that is used for deciding meta-election and puts them under meta-election, so when multiple meta-elections are evaluated in parallel, the don't interfere with each other. Summary of changes:
- Introduced a struct called `MetaEvent` to contain all per-event, per-meta-election data.
- Added map of `Hash` -> `MetaEvent` to `MetaElection`.
- Moved `meta_votes` to `MetaEvent`.
- Moved `observations` from `Event` to `MetaEvent`.
- Moved `interesting_content` from `Event` to `MetaEvent`.
- Moved `interesting_events` from `Parsec` to `MetaElection`.
- A full list of voters is now stored in decided `MetaElection`s, instead of just the count.
This PR also includes some refactoring.

MAID-3225: meta-election data

---

src/dump_graph.rs
src/gossip/event.rs
src/meta_voting/meta_elections.rs
src/observation.rs
src/parsec.rs
src/peer_list.rs

This PR implemented detection of invalid gossip creator. It splits the malice detection into two phases: ~before-add~ before-process and ~after-consensus~ after-process. Invalid gossip creator is currently the only type of malice detected in the after-process phase, because it requires the membership list to be initialised to work.
This PR also fixes an issue with initialising the membership list, where if the other-parent were created by us, the membership list would end up empty. It also simplifies membership list handling by letting the peer's id to be stored in their own membership list too. It was originally omitted to prevent redundancy, but it created lot of special cases and complicated the code.
Finally, this PR fixes a bug in the graph dumping where the meta-votes would be …

MAID-3055: detect invalid gossip creator

---

Cargo.toml
src/dev_utils/dot_parser.rs
src/dev_utils/mod.rs
src/gossip/event.rs
src/lib.rs
src/meta_voting/meta_elections.rs
src/meta_voting/meta_event.rs

This is only the first part of changes that will constitute MAID-3212.
If I may suggest something regarding reviewing - it will probably be much easier to review the final state of `dot_parser.rs` instead of the diff, as the file is essentially rewritten and very little remained the same. The rest of the files only have small diffs, so they should cause less headaches :wink:

MAID-3212: Switch the dot-parser to use the pom crate

---

input_graphs/parsec_functional_tests_unpolled_and_unconsensused_observations/alice.dot
src/parsec.rs

I'll add the WIP tag to this since I think it should be merged after #150 to avoid causing any more pain to that much larger PR.
It should be fairly easy to regenerate the dot file for this test once the dot-writing/parsing changes are in place.  This one was generated using the dot_gen tool with the following scenario:
```rust
let _ = scenarios
.add(
"parsec::functional_tests::unpolled_and_unconsensused_observations",
|env| {
let obs = ObservationSchedule {
genesis: peer_ids!("Alice", "Bob", "Carol", "Dave"),
schedule: vec![(0, AddPeer(PeerId::new("Eric")))],
};
Schedule::from_observation_schedule(env, &ScheduleOptions::default(), obs)
},
).file("Alice", "alice.dot")
.seed([1, 3, 1, 4]);
```

MAID-3233: add test for unpolled and unconsensused observations

---

input_graphs/parsec_functional_tests_handle_malice_invalid_gossip_creator/alice.dot
input_graphs/parsec_functional_tests_handle_malice_invalid_gossip_creator/bob.dot
src/parsec.rs

InvalidGossipCreator is when a node reports gossip from another node
that isn’t in their section.
_Note:_ the test is disabled and the PR marked as WIP as the implementation has not yet landed. It seems likely that it might need tuning once the test can be tested!

MAID-3056: Add test for InvalidGossipCreator

---

src/peer_list.rs

The peers field was accidentally left over and isn't actually used. A pretty minor change, probably the smallest in a while. But it's presence led me on a while goose chase when trying to understand the the code so I'd prefer to just get rid of it straight away.

Remove unused left over peers field in Peer struct

---

Cargo.toml

This also fixes a trivial clippy warning.

chore/build: make proptest a dev dependency

---

src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/schedule.rs
src/parsec.rs
tests/integration_tests.rs

This commit includes multiple changes:
1. Modify the testing framework to fail when a node raises invalid accusation
2. Modify the testing framework so a joining node always votes for all previous `Add`s and `Remove`s, in addition to `OpaquePayload`s
3. In `Parsec::from_existing`, do not initialise membership list of non-genesis peers. Instead, leave the initialization to when we receive their first event with other-parent.
4. When detecting `InvalidGossipCreator`, consider only the direct other-parent, instead of all ancestors.
5. Modify the `add_peers` integration test to start at 2 peers and add 8 more peers (for the total of 10) one by one. Also rename to `add_many_peers`.

Fix invalid InvalidGossipCreator accusations

---

.travis.yml
Cargo.toml
src/dev_utils/mod.rs
src/lib.rs

This trims the crate compiled for production a bit by feature-gating parts of the code that shouldn't be used in production, anyway.

Move the mock module behind a feature gate

---

benches/bench.rs
dot_gen/src/main.rs
examples/basic.rs
src/lib.rs
src/peer_list.rs
tests/integration_tests.rs

These two commits fix a couple of issues exposed when I ran the benchmark suite using the latest nightly compiler.  Certainly the unused results seem to be a worthwhile fix.  The removed lints could probably be delayed, but I'd think the sooner we start updating our libs the better.

Minor updates

---

src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/schedule.rs
src/parsec.rs
tests/integration_tests.rs

This modifies PARSEC so that opaque transactions that only require a single vote are handled correctly.
One of the bigger changes is the introduction of "interesting payload inheritance": if an event has an ancestor that contains a given interesting payload, and it is a viable interesting payload candidate (i.e. no self-ancestor carries it already), then it automatically becomes an interesting payload of this event as well. This was already happening indirectly in the absence of forks, but this change ensures that this desired property also holds if forks are present.
There are still possible performance enhancements to be made; TBD if they should be done as a part of this PR.

MAID-3248: Ensure PARSEC works with consensus on single opaque transaction

---

src/dev_utils/dot_parser.rs
src/hash.rs
src/observation.rs

It's useful for clients like routing to have the whole hash printed by the Debug trait. Let's print the whole one except for when dumping graphs.

MAID-3259: only shorten debug hashes for dump-graphs

---

tests/integration_tests.rs

The test for single-vote opaque transactions is sometimes failing - this PR marks it as ignored until the reason is found and fixed.

Temporarily ignore a failing test

---

src/block.rs
src/dev_utils/dot_parser.rs
src/dump_graph.rs
src/gossip/event.rs
src/meta_voting/meta_elections.rs
src/meta_voting/meta_event.rs
src/observation.rs
src/parsec.rs
src/peer_list.rs
src/round_hash.rs

This commit adds a map of observations to their hashes, and uses `ObservationHash`s extensively in place of `Observation`s to reduce the number of times we serialise and hash `Observation`s.

MAID-3257: avoid calling create_hash() as frequently

---

src/gossip/event.rs
src/parsec.rs

When we started evaluating wether events had interesting ancestors to
resolve an issue with votes becoming "unseen" due to forks, we
introduced a performance regression as checking wether an event has an
interesting ancestor is expensive.
Regain the performance in the happy case by only performing this check
when this event sees forks.

MAID-3261: chore/parsec: fix performance regression

---

src/dev_utils/peer.rs
src/dev_utils/schedule.rs
src/parsec.rs
tests/integration_tests.rs

This PR modifies the test framework so that it is much less likely to make too many network mutations at once (which caused the simulated section to stall and the test to fail), as well as fixes a bug in `is_observer`.

MAID-3260: fix the test for single-vote interesting events

---

src/dev_utils/dot_parser.rs
src/dev_utils/mod.rs
src/gossip/graph/mod.rs
src/gossip/mod.rs
src/gossip/packed_event.rs
src/lib.rs
src/meta_voting/meta_elections.rs
src/meta_voting/mod.rs
src/parsec.rs
src/peer_list.rs

Move the functional tests behind the mock feature gate so that `cargo test` works out of the box.

Move functional tests behind the mock feature gate

---

README.md
tutorial.md

Re-add dump-graphs unintentionally removed when updating parameters in tutorial.md.
Update README.md that need to be in sync with tutorial.md.
Keep the long name parameter for clarity.
Verify the command succeed.

docs/parsec: use dump-graphs and new parameters for command lines

---

src/block.rs
src/dev_utils/network.rs
src/gossip/event.rs
src/parsec.rs
tests/integration_tests.rs

This PR changes the way blocks are created. Now a block is signed only by peers who are still voters at the time of the block creation. If there are no such peers, the block is skipped. That can happen when a peer votes first and is removed shortly after, but the removal is consensused before the vote. 
This PR also implements minor optimizations by replacing comparisons of `Observation`s with  comparison of `ObservationHash`es in a couple of places.

Fix issue with invalid block signatory when ConsensusMode is Single

---

examples/basic.rs
src/mock.rs

Random names for the peers can cause issues when visualising the generated dot file. Pick human readable names if available to mitigate it.
Also pads `NAMES` with a few more entries. Wasn't sure which names to use, so I just checked a baby name website!

MAID-3264: Use human readable peer names in basic example

---

src/block.rs
src/dev_utils/dot_parser.rs
src/dev_utils/environment.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/record.rs
src/dev_utils/schedule.rs
src/dump_graph.rs
src/error.rs
src/lib.rs
src/meta_voting/meta_elections.rs
src/meta_voting/meta_event.rs
src/meta_voting/meta_vote_counts.rs
src/observation.rs
src/parsec.rs

This PR implements one part of MAID-3266: it makes it so that when we are in the `ConsensusMode::Single`, each voted opaque payload is outputted in its own block signed only by the single voter.

MAID-3266: Support single-vote blocks

---

src/lib.rs

This adds an overview of what consensus algorithms are, how PARSEC fits the picture and a brief summary of typical usage of this crate to the top-level documentation.
Suggestions on what to add/improve/remove are welcome.

MAID-2976: expand the documentation in lib.rs

---

src/error.rs
src/gossip/event.rs

When the hash of the other_parent doesn’t point to any known gossip event, `handle_request` and `handle_response` should return `Error<UnknownOtherParent>` or `Error<UnknownSelfParent>`.
Note in the original task `InvalidOtherParent`/`InvalidSelfParent` was specified.

MAID-3080/3083: Detect invalid self/other parent

---

src/dev_utils/dot_parser.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/proptest/schedule.rs
src/dev_utils/schedule.rs
src/parsec.rs
tests/integration_tests.rs

1. Fix the `Parsec::previous_interesting_content` function to return `None` in case the previous interesting content is empty. In that case we must perform the full computation, because there can be new interesting content that wasn't present in the previous meta-election.
2. Make `PeerRemovalGuard` more robust to handle edge cases.
3. Lower the gossip probability to speed the tests up, but increase the `adjustment_coeff` correspondingly, to make sure they still pass. Overall significant test performance increase.
4. Remove `prob_local_step` as it wasn't really used anymore (local step now happens on every step).
5. Some minor refactoring of the test framework

Fix and optimize the test framework + fix subtle bug in Parsec

---

src/dev_utils/dot_parser.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/schedule.rs
src/mock.rs
src/parsec.rs

1. During schedule generation, votes are now cast by all peers, not just by the active ones. This is because the status of a peer during schedule generation might not necessarily match its status during execution (because of `PeerRemovalGuard`). Removed and failed peers are skipped when actually casting votes durging execution.
2. In single-vote mode, any votes cast by peers that are scheduled for removal or fail anywhere in the schedule are not guaranteed to be consensused. The framework is updated to reflect this.
3. Re-queueing of schedule events that failed to be executed is changed to prevent single failed event to be tried over and over until the schedule is exhausted.

Fix several issues in the test framework

---

dot_gen/src/main.rs
input_graphs/functional_tests_handle_malice_genesis_event_creator_not_genesis_member/alice.dot
src/dev_utils/dot_parser.rs
src/dump_graph.rs
src/meta_voting/meta_elections.rs
src/parsec.rs

This PR trying to improve performance by reducing the number of events we need to traverse when calculating interesting content. It does so by caching all events that carry unconsensused payloads in the meta-election.
It also fixes two subtle bugs in the `previous_interesting_content` optimization. Details are explained in the corresponding commit message.

Perf optimization: cache unconsensused events in meta-election

---

src/meta_voting/meta_elections.rs

This fixes an issue with `previous_interesting_content` sometimes incorrectly returning empty collection.
Problem is that if we only update `unconsensused_events` for the current meta-election, the following situation can occur:
1. We decide the current meta-election, thus freezing it's `unconsensused_events`.
2. We keep adding new meta-events to that meta-election, because we are still evaluating it from the point of view of other peers.
3. Some time later, we add an event that carries an observation X. This event is NOT added to the `unconsensused_events` of that meta-election
4. So from that point on, no meta-event created for that meta-election will ever have X among its interesting content.
5. So `previous_interesting_content` is now broken, because it might return a vec that doesn't …

Update unconsensused events also in previous meta-elections

---

src/dev_utils/dot_parser.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/record.rs
src/dump_graph.rs
src/error.rs
src/functional_tests.rs
src/gossip/cause.rs
src/gossip/content.rs
src/gossip/event.rs
src/gossip/event_context.rs
src/gossip/event_hash.rs
src/gossip/graph/ancestors.rs
src/gossip/graph/event_ref.rs
src/gossip/graph/mod.rs
src/gossip/messages.rs
src/gossip/mod.rs
src/gossip/packed_event.rs
src/meta_voting/meta_elections.rs
src/meta_voting/meta_event.rs
src/observation.rs
src/parsec.rs
src/peer_list/mod.rs
src/peer_list/peer.rs
src/vote.rs

This PR removes some fields from `Event` that weren't necessary:
- `self_parent_hash: EventHash` and `other_parent_hash: EventHash` - can be looked up by `self_parent: EventIndex` and `other_parent: EventIndex`.
- `creator_id: P` - can be looked up by `creator: PeerIndex`
- `vote: Vote<T, P>` - replaced by `VoteKey`, which can be used to look up the actual `Vote`.
In order to do this, `Content` and `Cause` are now generic over the type of vote (`Vote` or `VoteKey`), the type of event indentifier (`EventHash` or `EventIndex`) and the type of peer identifier (`PublicId` or `PeerIndex`). `Event` now contains the ones specialized with `VoteKey`, `EventIndex` and `PeerIndex`, whereas `PackedEvent` has `Vote`, `EventHash` and `PublicId`.
`Event` is no longer generic over `T: NetworkEvent` which …

MAID-3276: remove redundant fields from Event

---

src/dump_graph.rs
src/parsec.rs

We need to consider only events seen by the current event, otherwise we might collect more payloads than we should which would result in the set of interesting content being inconsistent between peers.

Fix bug in set_interesting_content

---

input_graphs/consensus_with_forks/alice.dot
input_graphs/consensus_with_forks/bob.dot
input_graphs/consensus_with_forks/carol.dot
input_graphs/consensus_with_forks/dave.dot
input_graphs/consensus_with_forks/eric.dot

PR 212 changed dot file's format. With `start_index` removed and introduced `unconsensused_events`.
However, the `consensus_with_fork` test is disabled, hence there is no error exposed and left the dot files forgot to be updated at that time.

fix/test: update testing dot files

---

src/meta_voting/meta_vote.rs

The colouring work from Bart exposed an `one event late` issue:
that is for new peer's event_1, although it already sees other voters' meta decisions, it will only be at event_2 that the new peer will reached the same perspective.
This PR contains a fix resolving this issue.

MAID-3271 investigate issue of new peer's event_1 cannot reach consensus

---

src/dev_utils/network.rs
src/dev_utils/peer.rs
src/parsec.rs

This change avoids the blocks handled by non-active test nodes as counting towards the voting quorum.  It also fixes a minor bug in the test code whereby failed peers were treated as running, and a logging statement which triggers a subtraction with overflow.

bugfix/tests: fix various issues in tests

---

src/functional_tests.rs
src/gossip/event.rs
src/gossip/packed_event.rs
src/observation.rs
src/parsec.rs
src/peer_list/mod.rs
src/peer_list/peer.rs

The initial raison d'être for having the `CandidateAccompliceAccusation` buffer was that the `Accomplice` malice was detected at a different event than when we could act on it. However since it was decided to repoint the accusations anyway to the event where we're actually certain we don't really need it anymore.
As a nice side effect, this should get rid of duplicate accusations being generated in certain scenarios.

MAID-3280: fix duplicate Accomplice accusations

---

dot_gen/Cargo.toml
dot_gen/src/main.rs
src/dev_utils/mod.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/peer_statuses.rs
src/dev_utils/schedule.rs

Upon removing a peer in the test network, we failed to recheck existing peers which were transitioning to Added or Removed to see if the new lower number of members meant that a supermajority was valid now.
Rather than persist with the `PeerRemovalGuard` which effectively represented a "God view" of the network in terms of the joining and leaving states of the peers, there is now a network view held as a
member of the `Peer` struct.
This avoids synchronisation problems and allows better encapsulation of `Peer` by tying the transition between states into `Peer` methods.
This also moves the `PeerStatuses` struct unchanged into its own file to avoid cluttering peer.rs.

fix/tests: fix an issue whereby peers' states were not updated

---

Cargo.toml
src/gossip/event.rs
src/gossip/mod.rs
src/lib.rs
src/parsec.rs
src/parsec_helpers.rs
src/peer_list/peer_index.rs

When we have duplicate payloads in 'unconsensused_events' voted by different peers, only call is_interesting_payload on unique playloads.
This situation occurs with ConsensusMode::Supermajority, or for adding/removing peers where we can have 2/3*peer_count duplicate events.
Add tests to support changes:
-A bug was introduced in initial implementation, not caught by `cargo test` and was difficult to debug.
-Split testable free function in initial commit to ensure clear diff on this update without unit tests.
-This free function has its dependecy on Parsec injected as closure and use the new AbstractEvent trait so a light weight and easily configurable Event stub/mock can be used in tests.
Note on tests:
-Use AAA(Arrange/Act/Assert) test pattern for test function as it ensure test remain …

Scalability: is_interesting_payload

---

benches/bench.rs
src/dev_utils/record.rs
src/parsec.rs

The series of benchmark with different section size aims to provide
scalability information. This only work if they reach the same
consensus.
Consensus can be reached before the create_sync_event occurs.
In this case, the dot file replay needs to create a new request so all
the gossip event that were processed to reach the consensus are given.
This request could be considered as spam as it will send events from
multiple nodes that do not have a common parent.
cargo test
cargo bench --test (no pannic)
When there is a problem, the benchmark fails with:
"
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `(9, [a9d4c41b69.., e2eabbc898.., d08b8bc951.., 2de98dadad..,
8df8111faf.., c93ff2cda7.., 536064db2b.., 9daa8f8e91..])`,
right: `(1, [a9d4c41b69..])`', …

fix/parsec: ensure benchmarks reach same consensus as .dot file

---

src/dev_utils/dot_parser.rs
src/functional_tests.rs
src/gossip/cause.rs
src/gossip/content.rs
src/gossip/event.rs
src/gossip/event_context.rs
src/gossip/mod.rs
src/observation.rs
src/parsec.rs

Refactor to simplify future work, particularly with performance.
In order to dump all events received on dump-graph, we may want to
unpack all events up-front. Using EventContextMut made it unclear whether it
was safe.
Also, observation is populated on unpack, but we may not add the event
to the graph in case of malice. This maybe something we want to change.
Test:
cargo test --features=testing,malice-detection

refactor/parsec remove EventContextMut

---

src/meta_voting/meta_election.rs
src/meta_voting/meta_vote.rs
src/meta_voting/meta_vote_counts.rs
src/parsec.rs

Address performance issue related to set_meta_votes.
The first 2 commits apply smaller updates close to refactoring, but they do change behavior:
-First use references to vector instead of cloning the contents.
-Then: like for parent_meta_votes ignore empty meta_votes everywhere meta_votes was called: rename to populated_meta_votes
Finally Update code to avoid duplicate lookup highlighted by 'perf' and 'callgrind'
```
RUSTFLAGS=-g RUST_BACKTRACE=1 cargo bench --features=testing -- --baseline=master-da5b291
minimal                 time:   [726.91 us 744.71 us 764.01 us]
change: [-17.884% -14.460% -10.985%] (p = 0.00 < 0.05)
Performance has improved.
static                  time:   [3.7173 ms 3.7292 ms 3.7455 ms]
change: [-12.445% -12.002% -11.570%] (p = 0.00 < 0.05)
Performance has …
```

Perf fix vote collection

---

.travis.yml
scripts/clippy
scripts/tests

Hi Pierre/JP,
We don't actually need more than 1 stage for this. This setup runs 4 jobs in parallel:
* clippy commands on Linux
* clippy commands on OSX
* test commands on Linux
* test commands on OSX
Neither the test or clippy commands individually take long to run after compilation has been done, so it's not really worth separating them out into parallel jobs, since each parallel job spins up a fresh machine and would do re-compilation.
I think this is the best you would get out of Travis. Removing OSX clippy wouldn't save that much time since the tests take longer to run anyway, and the total time taken for this is whatever one of these 4 jobs takes the longest to run.
Cheers,
Chris

Travis stages

---

dot_gen/src/main.rs
input_graphs/dev_utils_record_tests_smoke_other_peer_names/annie.dot
src/dev_utils/dot_parser.rs
src/dev_utils/record.rs
src/gossip/graph/mod.rs
src/hash.rs
src/lib.rs
src/mock.rs
src/parsec.rs

Allow replay dump graphs that contain peer Ids not in our list of hard coded names.
It is the initial step in replaying dump graph from routing tests, but does not handle peer ids with the same initial (multi-char short name), or non alpha numerical characters yet(id sanitizing).
Add smoke test to support this current and future development.
Note: .dot file does not contain everything, so we need to ignore some things in our comparison:
- consensus history: the .dot file does not contain the last consensused block as the dump occurs before it is added to the history
- The graph of events may contain a fake request that send us the remaining gossip events if the dump graph was produced on a gossip event that was not ours (consensus when processing another peer gossip event).

Dot files with generic peer ids

---

src/dev_utils/dot_parser.rs
src/dump_graph.rs
src/functional_tests.rs
src/meta_voting/meta_election.rs
src/meta_voting/meta_event.rs
src/meta_voting/mod.rs
src/parsec.rs
src/peer_list/mod.rs

This is simply #233 rebased on current master.
1. Try optimize the computation of observer. Before we calculated the set of "observees" for every event and then use it to determine if the event is observer. But we don't need to keep the observees around, we only need to know if the event is observer.
So we now compute the observer status right away and store the observees only if the event IS observer. This saves memory and might also improve performance a bit. I was also hoping to reuse the observer status in subsequent meta-elections, but that didn't work out.
2. Mostly refactoring to simplify how we calculate interesting content. This also improves the performance: Only calculate interesting content when creating new meta-event, not when reprocessing them. On membership-change, clear …

Less reprocessing

---

src/dev_utils/network.rs
tests/integration_tests.rs

This resolves an issue in the test framework where we would add many peers in a short period, and then start dropping the existing ones as the new ones are voted in.  When that happened, a new peer could end up not receiving gossip from any of the peers with which it was initialised, and would hence be stalled as it wouldn't accept messages from any of the new peers.
This commit changes the test framework to only allow the addition and voting for addition of new peers if that would retain a supermajority of "Joined" peers out of "Joined and Joining" ones.  When this is not the case, addition and voting is postponed, not cancelled.

fix/integration_tests: avoid adding peers too aggressively

---

src/functional_tests.rs
src/parsec.rs
src/peer_list/mod.rs
src/peer_list/peer.rs

This PR fixes the following issue:
1. Node (A) is removed from the section
2. New node (B) joins and recieves a gossip message from someone
3. The events in the gossip message might be ordered so that an event from A is before an event which triggers the consensus to add A (*)
4. But B doesn't yet know A, so it reject that event and return error, never processing the rest of the gossip message
5. This might sometimes prevent consensus to be reached and make the section disfunctional
The fix is to make sure that any event from A always comes after the event which triggers the consensus on add A. This is achieved by postponing inserting our events into the graph until we become voter - that is - we are either genesis node or we have observed consensus on adding ourselves.
(*) This is …

fix/parsec: create own events only when we become voter

---

benches/bench.rs

Criterion is truncating the benchmark names to 64 characters and
confusing baselines for tests that start with the same long sequence of
characters.
See https://github.com/bheisler/criterion.rs/issues/272
Work around this bug by putting the test name (most significant letters
of the benchmark) first.

fix/bench: workaround criterion bug

---

src/dev_utils/dot_parser.rs
src/dump_graph.rs
src/lib.rs
src/meta_voting/meta_election.rs
src/meta_voting/mod.rs
src/observation.rs
src/parsec.rs

This address 3 different issue that occur when having many events and that are blocking generating benchmarks for multiple 1000's of events.
1- is_already_interesting_content doing linear search on events.
2- On consensus, avoid expensive vote resolving if not the needed payload key.
3- Avoid N^2 on number of unconsensused events in num_creators_of_ancestors_carrying_payload
Combined performance Test results
time cargo bench --features=testing -- --baseline pr267 t1024
a_node4_opaque_evt1024 - bench_section_size_evt1024_interleave
time:   [101.69 ms 101.74 ms 101.85 ms]
change: [-68.700% -68.632% -68.576%] (p = 0.02 < 0.05)
Performance has improved.
a_node8_opaque_evt1024 - bench_section_size_evt1024_interleave
time:   [293.68 ms 317.17 ms 328.20 ms]
change: [-71.050% -69.783% -67.682%] …

Meta election perf

---

src/parsec.rs

Within the current test of concensus_with_fork, at step 34, Eric accused Alice of Fork.
However, at step 47 Carol still accused Eric with Accomplice. This situation happens to many other accusations as well (that is A accused already, but B still cast A as accomplice).
This issue is resovled in this PR by ensuring that: accomplice check is only carried at the events that are not request/response/accusation .

MAID-3287 fix/parsec: avoid invalid accomplice accusation

---

.travis.yml
Cargo.toml
scripts/clippy

Make Parsec a workspace to address issues with multi crates and travis.
Fix version discrepancies detected by workspace.
Remove osx clippy from travis.

Fix clippy and travis

---

src/dev_utils/network.rs

Fix issue with the last version of PR #274 
Test:
Verify regenerating benchmark for 1024 events are as commited (with
consensus history).

fix/dev_utils: disable the correct peer consensus

---

dot_gen/src/main.rs
input_graphs/functional_tests_our_unpolled_observations_with_consensus_mode_single/alice.dot
src/block.rs
src/dev_utils/dot_parser.rs
src/dev_utils/mod.rs
src/dev_utils/record.rs
src/dump_graph.rs
src/functional_tests.rs
src/gossip/cause.rs
src/gossip/event.rs
src/parsec.rs

The bug was that when using `ConsensusMode::Single`, `our_unpolled_observation` sometimes returned observations that have already been polled. This PR also contains a test case exposing the bug.

MAID-3293: Fix our_unpolled_observations

---

src/gossip/abstract_event.rs
src/gossip/event.rs
src/gossip/graph/event_ref.rs
src/gossip/mod.rs
src/meta_voting/meta_election.rs
src/parsec.rs
src/parsec_helpers.rs
tests/integration_tests.rs

This PR changes the implementation of the detection of interesting event to not be based on the `sees` relation, but instead on the `is_descendant`. This makes it resilient to forks as the result of `is_descendant` never changes retroactively (unlike `sees`).

MAID-3296: Fix interesting event detection in presence of forks

---

Cargo.toml
dot_gen/src/main.rs
src/dev_utils/dot_parser.rs
src/dev_utils/record.rs
src/error.rs
src/functional_tests.rs
src/gossip/event.rs
src/gossip/graph/mod.rs
src/gossip/messages.rs
src/gossip/packed_event.rs
src/observation.rs
src/parsec.rs

This PR adds validation that incoming messages are correct (wrt the sender correctly following the `Requesting` → `Request` → `Response` flow) and also similar validation for all sync events as they're added to the graph.
In the case of the former, the message isn't handled at all (no events are added to our graph) and an accusation of `UnprovableMalice` is made against the sender.
To allow efficient checking that a sync event's corresponding descendant hasn't yet been added, a hash-set containing all the `Requesting` and `Request` sync events which don't yet have their partner `Request` or `Response` sync event has been added to `Graph`.
This also required the `dev_utils::Record` to be updated for the case where, at the end of iterating through the parsed dot file creating actions, we …

MAID-3282: add malice protection for Requesting type

---

input_graphs/functional_tests_sees/alice.dot
src/dev_utils/dot_parser.rs
src/dev_utils/macros.rs
src/dev_utils/misc.rs
src/dev_utils/mod.rs
src/dev_utils/peer.rs
src/dev_utils/record.rs
src/dump_graph.rs
src/functional_tests.rs
src/gossip/event.rs
src/gossip/event_utils.rs
src/gossip/graph/mod.rs
src/gossip/mod.rs
src/lib.rs
src/parsec.rs
src/peer_list/peer_index.rs

This PR makes Parsec resilient to forks. The bulk of the PR deals with making sure the `sees` function gives consistent results that depend only on the structure of the graph and not on the order in which events are received. The PR also improves the DOT parser and dumper to support graphs with forks.

MAID-2939 + MAID-3204 + MAID-3283 + MAID-3292: Fork resilience

---

src/meta_voting/meta_election.rs
src/parsec.rs

1. Do not stop the search when the current event has no meta-votes. Continue on the next event instead.
2. When new meta-election is started and there are no remaining unconsensused events, set `continue_consensus_start_index` to `graph.len()` instead of `usize::MAX`, so that events added afterwards are still considered when searching for coin value.

Fix coin value search

---

src/meta_voting/bool_set.rs
src/meta_voting/meta_vote.rs
src/parsec.rs

This PR modifies the way in which meta-votes are assigned to events:
1. First, temporary meta-votes are calculated using no coin tosses
2. Coins are tossed using the temporary meta-votes
3. Final meta-votes are calculated using the temp meta-votes and the coin tosses

MAID-3134: Calculate coin tosses after calculating meta-votes

---

src/dev_utils/schedule.rs
src/parsec.rs
src/peer_list/mod.rs
src/peer_list/peer.rs
tests/integration_tests.rs

This PR fixes issues that caused the `consensus_with_fork` test to fail:
1. Update the test framework to account for raised accusations when calculating expected number of blocks.
2. Modify parsec so that it accepts events even from removed peers if those peers haven't yet reached the consensus on their own removal.

MAID-3301: Fix failures in the consensus_with_fork test when malice-detection is enabled

---

src/dev_utils/dot_parser.rs
src/dump_graph.rs
src/gossip/cause.rs
src/gossip/event.rs
src/observation.rs

This PR contains the work of making dot file dumper & parser supports malice accusation.
So far, there are only two malice supported: Fork and InvalidAccusation. 
As the testing case that is currently being worked on only requires these two.
To support other malice types, the main blocking point is how a `packed_event` to be dumped and parsed. This will require a further discussion.

Make dot file dumper & parser supports malice accusation

---

src/parsec.rs

detect_duplicate_vote used to be a massive bottleneck for benchmarks
with many events as we would spend a lot of time fetching the
observations from the ObservationStore (which is a BTreeMap).
The ObservationKey uniquely identifies a given payload with its hash,
so these BTreeMap accesses were actually unnecessary.
Full benchmark results:
```
minimal - benches       time:   [1.6240 ms 1.6314 ms 1.6458 ms]                             
change: [+13.670% +14.565% +15.216%] (p = 0.02 < 0.05)
Performance has regressed.
static - benches        time:   [5.0346 ms 5.0638 ms 5.0785 ms]                           
change: [-0.2593% +0.1510% +0.5983%] (p = 0.64 > 0.05)
No change in performance detected.
dynamic - benches       time:   [3.3536 ms 3.3643 ms 3.3725 ms] …
```

Fix the most obvious performance pessimization caused by malice detection

---

src/error.rs
src/functional_tests.rs
src/gossip/messages.rs

This removes a macro used by the functional tests which could easily be misused, an example being highlighted by [this comment thread](https://github.com/maidsafe/parsec/pull/300#discussion_r276644857).

chore/test: remove macro

---

src/observation.rs

maidsafe/routing currently is duplicating this bit of functionality.

chore/observation: expose `is_opaque` publicly

---

src/dev_utils/dot_parser.rs
src/dump_graph.rs
src/meta_voting/bool_set.rs
src/meta_voting/meta_vote.rs
src/meta_voting/meta_vote_counts.rs
src/meta_voting/meta_vote_values.rs
src/meta_voting/mod.rs
src/parsec.rs

This PR contains the work of refactor the previous MetaVote to separate concerns.
Also, unit tests for the new struct MetaVoteValues, and unit tests for the refactored MetaVotes are created to improve the test coverage.

refactors MetaVote and creates unit tests for it

---

examples/basic.rs
input_graphs/benches/minimal.dot
input_graphs/dev_utils_record_tests_smoke_other_peer_names/annie.dot
input_graphs/functional_tests_unpolled_observations/alice.dot
src/dev_utils/dot_parser.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/record.rs
src/dump_graph.rs
src/functional_tests.rs
src/observation.rs
src/parsec.rs

- Add a new `genesis_info` parameter to `Parsec::from_genesis` for specifying the related_info on the genesis event.
- Some dot files had to be modified/regenerated because the hash of `Observation::Genesis` changed.
- A bogus clippy lint silenced by slightly reshuffling the code (clippy issue: https://github.com/rust-lang/rust-clippy/issues/4133)

Add related_info to Observation::Genesis

---

Cargo.toml
src/id.rs
src/key_gen/LICENSE-APACHE
src/key_gen/LICENSE-MIT
src/key_gen/mod.rs
src/key_gen/rng_adapter.rs
src/key_gen/tests.rs
src/lib.rs
src/mock.rs

Bring up the code that allow doing DKG:
- Copy files from github.com/poanetwork/hbbft for DKG
- Integrate/update to fix our own infrastructure and ensure test pass.
- Clean up API to work well with routing.
Notes:
- We could imagine splitting that into its own crate but that may create friction at this point.
- threshold_crypto as rand 6.5 in its API. To avoid tight coupling now and in the future make an adapter inspired by similar code in HBBFT that was used before they synced their dependencies.

DKG bring up: integrating code imported for HBBFT

---

src/block.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/schedule.rs
src/dump_graph.rs
src/key_gen/dkg_result.rs
src/key_gen/message.rs
src/key_gen/mod.rs
src/key_gen/rng_adapter.rs
src/key_gen/tests.rs
src/lib.rs
src/observation.rs
src/parsec.rs
tests/integration_tests.rs

Execute DKG adding DkgMessages to the gossip graph:
- All the DkgMessages are internal and do not come out as blocks when
consensused. They still need consensus as order is critical.
- A function `handle_dkg_start_consensus` start the DKG process.
This is a place holder as we need all node to start the dkg at the
same block, so it will need to be triggered by a consensus event.
- A new `Block` is created when a Dkg complete. It is a strange block
as it does not have any proofs, and while all participant will get
that block, the DkgResult will not be shared:
=> The PublicKeySet will be shared by all
=> The SecretKeyShare will be unique to each participants, and
observers will have None for it.
- Using a block like this does provide benefit for the initial bring up:
=> It does fit with the …

complete DKG as part of Parsec gossip graph.

---

examples/basic.rs
src/dev_utils/environment.rs
src/dev_utils/mod.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/proptest/schedule.rs
src/dev_utils/pseudo_random.rs
src/dev_utils/record.rs
src/dev_utils/schedule.rs
src/dump_graph.rs
src/error.rs
src/functional_tests.rs
src/key_gen/mod.rs
src/key_gen/tests.rs
src/lib.rs
src/observation.rs
src/parsec.rs
tests/integration_tests.rs

This change create a public way to start a DKG and get a result and update associated test.
This change does not address replaying dump-graph that include DKG.
Note:
-Initial commit started with an approach that avoided storing Rng in Parsec but was flawed.
We have to trigger the DKG on event consensus whether we voted for it yet or not.
-The rang::Rng in the interface make consumer of Parsec depend on a specific version of rand.
This can be addressed if we decide it would be a better approach when handling dump-graph and replay, possibly using std::io::Read as a stable interface.
Closes #323

initiate DKG using a consensused event

---

dot_gen/src/main.rs
input_graphs/dev_utils_record_tests_smoke_dkg/alice.dot
src/dev_utils/dot_parser.rs
src/dev_utils/mod.rs
src/dev_utils/pseudo_random.rs
src/dev_utils/record.rs
src/dump_graph.rs
src/key_gen/mod.rs
src/key_gen/parsec_rng.rs
src/mock.rs
src/parsec.rs

Closes #324 
We need additional info to be able to replay the DKG:
- We need Parsec to be able to recreate DKG part, this depend on the
output of the injected RNG: Store that output to be able to replay
it.
- We need to be able to dump/parse the Dkg Parts and Acks:
Dump them in the comment only to not add too much noise to the graph
(very long), and parse them back.
- Also parse DkgStart.
During replay:
- We need to create the ReplayRng for Parsec.
- We need to ignore/not vote for our own DkgMessages as parsec will
generate them.
Make the fake encrypt used for DKG deterministic so we can replay it.
Notes:
-Adding extra parameter to dump_graph to_file was triggering to many
param warning: Replace with a struct.
-Only write out rng if some values were output to avoid changing
existing dot …

feat/parsec: dump-graphs output needed info and can replay with DKG

---

src/block.rs
src/dump_graph.rs
src/key_gen/dkg_result.rs
src/key_gen/mod.rs
src/key_gen/tests.rs
src/observation.rs
src/parsec.rs
tests/integration_tests.rs

Closes #326 
Test and fix the code to allow DKG support for Routing section split.

allow multiple DKGs with partial participants to support split

---

dot_gen/src/main.rs
input_graphs/dev_utils_record_tests_smoke_dkg/alice.dot
src/dev_utils/dot_parser.rs
src/dev_utils/network.rs
src/dev_utils/peer.rs
src/dev_utils/peer_statuses.rs
src/dev_utils/schedule.rs
src/functional_tests.rs
src/mock.rs
src/parsec.rs
src/peer_list/mod.rs
src/peer_list/peer_state.rs
tests/integration_tests.rs

The bulk of the feature is in `feat/parsec: support non voters DKG`
Preceding commits and follow up refactor and extend testing. 
To support adding a new elder in routing we will likely need to run the
DKG before adding the node to the Parsec Voters.
Moreover, to support split in the context of node ageing, we will need
to support DKGs with non voters.
In order to support this flow, the gossip will contain non voters
gossip. (This could also happen when a voter is removed)
More details in the commit comments.

DKG with non voters participating in gossip

---

dot_gen/src/main.rs
input_graphs/dev_utils_record_tests_smoke_partial_dkg/alice.dot
src/dev_utils/dot_parser.rs
src/dev_utils/record.rs
src/dump_graph.rs
src/key_gen/mod.rs
src/parsec.rs

To allow tests that load Parsec using `Parsec::from_parsed_contents`
when a DKG is in progress, dump existing KeyGen as serialized data
and reload them.
This is a very basic facility, and we may want to update it in the
future to provide more useful information in the dump-graphs.
Update dot_gen to support extracting a specific dump in a serie so
we can pick a graph that contain a DKG in progress.
Test:
Add new test that exercise dump and reload.

feat/parsec: dump and reload KeyGen

---

src/dump_graph.rs
src/gossip/event.rs
src/gossip/graph/mod.rs
src/hash.rs
src/meta_voting/meta_event.rs
src/observation.rs
src/peer_list/mod.rs
src/peer_list/peer.rs
src/peer_list/peer_index.rs

As part of testing I ran the following combinations of feature flags (seems manual, probably should automate...)
```
cargo test $@ --release
cargo test $@ --release --features=testing
cargo test $@ --release --features=malice-detection
cargo test $@ --release --features=mock
cargo test $@ --release --features=dump-graphs dot_parser
cargo test $@ --release --features=testing,malice-detection
cargo test $@ --release --features=testing,mock
cargo test $@ --release --features=testing,dump-graphs dot_parser
cargo test $@ --release --features=malice-detection,mock
cargo test $@ --release --features=malice-detection,dump-graphs dot_parser
cargo test $@ --release --features=mock,dump-graphs dot_parser
cargo test $@ --release --features=testing,malice-detection,mock
cargo test $@ --release …
```

Fix warnings introduced in rustc 1.38

---

src/dev_utils/schedule.rs
src/parsec.rs
tests/integration_tests.rs

Routing start its test with a single voter, then we start DKG with
the two node forming the next Elder group.
This test was not working as the special handling of single voters
was making the DkgPart beeing consensused again and again.
=> Use same process to find consensus vote when there is a single
voter.
=> Ensure there are sync event so consensus can be found with a
single voter and no one else to gossip
Update scheduler so additional events are added even for a single
voter.
Note:
- Single voter now also require create_gossip to be called on
themselves to progress.
Test:
Clippy + tests.

fix/parsec: handle DKG with a single voter

---

src/parsec.rs
src/peer_list/peer.rs

This feature is required by the routing work of replace parsec::DKG with BLS-DKG crate.

feat/parsec: adding gossip peers by force
