- src/parsec.rs
implement see/strongly_see;
implement collect meta votes when crawling along the gossip_graph
> MAID-2764 implement see/strongly_see; implement collect meta votes

- src/dump_network.rs
To debug the gossip graph, knowing which events carry a vote may be
quite useful.
> feat/parsec: highlight votes

- src/meta_vote.rs
When meta-votes are updated, their own changes are now considered at each stage of the calculation.  This also ensures that once a decision has been made at a given round and step, it persists from then on.
> MAID-2864: update meta-votes properly

- src/dump_network.rs
- src/gossip/event.rs
- src/parsec.rs
This is one of the bugs found when testing the integration tests (MAID-2864)
> MAID-2864: Fix set valid blocks carried

- README.md
- tutorial.md
We want for someone landing on the repo to be able to generate graphs
and get a feel for how PARSEC works.
This small tutorial should be enough to get the interested explorer
started.
> MAID-2921: doc/parsec: write short getting started guide

- tests/utils/environment.rs
- tutorial.md
Improve the tutorial with a few minor fixes.
Try and guide users towards sharing their RNG seed if they need help as that would allow us comment on the specific scenario they ran.
Print the RNG seed in successful integration tests to enable community members to ask precise questions.
> Fixup tutorial

- .travis.yml
- appveyor.yml
- examples/basic.rs
- src/block.rs
- src/dump_graph.rs
- src/lib.rs
- src/meta_vote.rs
- src/parsec.rs
- src/round_hash.rs
- tests/integration_tests.rs
- tests/utils/network.rs
- tests/utils/schedule.rs
nightly to 2018-07-07
clippy to 0.0.212
rustfmt to 0.99.2
> [MAID-3107] chore/ci: update scripts to Rust stable 1.28.0

- Cargo.toml
- tests/integration_tests.rs
- tests/utils/environment.rs
- tests/utils/mod.rs
- tests/utils/network.rs
- tests/utils/proptest/bounded.rs
- tests/utils/proptest/environment.rs
- tests/utils/proptest/mod.rs
- tests/utils/proptest/schedule.rs
- tests/utils/schedule.rs
This is @fizyk20's PR: https://github.com/maidsafe/parsec/pull/58, rebased and fixed after compiler update.
This is so we can merge it while he is on holidays.
> Implement testing with Proptest

- src/parsec.rs
When checking whether we shall stop waiting to toss a coin, check
along the events created by the event's creator.
> MAID-3103 & MAID-3105: coin toss correction

- .travis.yml
- Cargo.toml
- appveyor.yml
- src/lib.rs
- src/parsec.rs
Specifically this is to make the new log_or_panic macro in maidsafe_utilities available to Parsec.
> MAID-2965: update dependencies

- src/parsec.rs
This makes the notion of an observer in the code compatible with the
whitepaper. The whitepaper defines an observer as the first event
created by a peer that strongly sees a supermajority of events carrying
valid blocks. The old `is_observer` function (renamed to
`has_supermajority_observations`) was checking for a supermajority, but
not that it's the first such event. The new `is_observer` function checks
both parts of the condition.
> MAID-3001: extract is_observer method

- src/gossip/cause.rs
- src/gossip/content.rs
- src/gossip/event.rs
- src/lib.rs
The second half of MAID-3010. The first half is to be done later.
> MAID-3010: Test Event construction

- src/parsec.rs
Note: this PR is based on #91, so that one has to be merged first.
> MAID-3033: handle adding peers

- src/dev_utils/schedule.rs
For now, we will make new peers vote for old observations in tests, so that it is easier to set expectations about the outcome (an event not getting consensused because of the peers witnessing it not being a supermajority is a valid situation, but not predictable in tests and so undesirable).
> MAID-3192: workaround

- src/parsec.rs
MissingGenesis malice is when a node that is part of the genesis group creates an event with no Observation::Genesis immediately after its initial event.
> MAID-3071: Add test for MissingGenesis

- src/meta_voting/meta_elections.rs
- src/parsec.rs
- src/peer_list.rs
The fixes:
1. The decided payload was incorrectly computed when deciding old meta-elections, because the payload computation relies on `interesting_events` and `interesting_content`, but those properties are not per-meta-election, and are reset when the current meta-election is decided. The fix is to put the decided payload into the meta-election itself when it is decided for the first time, then reuse on subsequent decidings.
2. Similar to the above issue, but caused by the number of voters being different between when the meta-election is decided for the first time and for the subsequent times. Happened when deciding observations that change the number of voters (`AddPeer`, ...). Fix is similar to point 1 - the number of voters is stored in the meta-election.
Other changes:
1. Keep our …
> MAID-3219: Fix issues with per-peer membership list

- input_graphs/parsec_functional_tests_handle_malice_invalid_accusation/carol.dot
- src/parsec.rs
Also fix a bug in the invalid accusation test.
> Fix: Avoid detecting self-malice

- .travis.yml
- Cargo.toml
- appveyor.yml
- src/dev_utils/dot_parser.rs
- src/dev_utils/mod.rs
- src/gossip/packed_event.rs
- src/parsec.rs
To allow easy integration with routing place malice detection behind a feature gate, that way latest master of parsec can easily be used.
> MAID-3251: feature gate malice detection

- input_graphs/parsec_functional_tests_handle_malice_handle_fork/bob.dot
- input_graphs/parsec_functional_tests_handle_malice_handle_fork/dave.dot
- src/dev_utils/dot_parser.rs
- src/parsec.rs
This PR adds a functional test for fork detection.
It also improves the dot parser in a few places, so that it will be able to handle graphs with forks.
This PR requires #152 to be merged first.
> MAID-3047: test fork detection

- benches/bench.rs
- dot_gen/src/main.rs
- input_graphs/benches/dynamic.dot
- input_graphs/benches/static.dot
- src/dev_utils/dot_parser.rs
- src/dump_graph.rs
- src/meta_voting/meta_elections.rs
- src/parsec.rs
This PR improves performance by reducing the number of events that are reprocessed after each consensus. It achieves that by computing the topological index of the first event that carries unconsensused observation, and reprocesses only from that event. Also, when scanning for interesting content, it only considers events from that index on.
This PR also adds more complex benchmarks and decreases benchmark sample size to reduce their runtime.
> MAID-3256: Less reprocessing

- src/meta_voting/meta_elections.rs
- src/parsec.rs
Just some additional traces that helped me find the reason behind latest issues.
> Add some trace calls for easier debugging

- tutorial.md
tutorial refers to older versions
> updating cargo commands

- dot_gen/src/main.rs
- input_graphs/functional_tests_handle_malice_accomplice/alice.dot
- input_graphs/functional_tests_handle_malice_accomplice/bob.dot
- input_graphs/functional_tests_handle_malice_accomplice/carol.dot
- src/functional_tests.rs
- src/gossip/event.rs
- src/gossip/mod.rs
- src/gossip/packed_event.rs
- src/gossip/split_on_first.rs
- src/observation.rs
- src/parsec.rs
Detect when a peer relays us malice that they themselves have not raised any accusations for.
> MAID-3049: detect accomplice malice

- input_graphs/consensus_with_forks/alice.dot
- input_graphs/consensus_with_forks/bob.dot
- input_graphs/consensus_with_forks/carol.dot
- input_graphs/consensus_with_forks/dave.dot
- input_graphs/consensus_with_forks/eric.dot
- src/dev_utils/dot_parser.rs
- src/dev_utils/mod.rs
- src/dev_utils/network.rs
- src/dev_utils/peer.rs
- src/meta_voting/meta_elections.rs
- src/parsec.rs
- tests/integration_tests.rs
This adds a test that leads the nodes to arrive at split consensus with the current code (most of the time).
The code is pretty hacky, so I'm open to comments suggesting how to make it better. The main idea is that we initialise 5 peers using dot-graphs and then let them gossip to each other according to a generated schedule. The graphs are prepared in a way that leads to split consensus most of the time (not 100%, though - might be another area that needs to get fixed).
The test failures are expected while MAID-3164 is not yet completed.
> MAID-3203: test whether a fork can break consensus

- src/functional_tests.rs
- src/parsec.rs
Delay accomplice accusations until we've seen in the graph that they've really omitted the accusation.
> MAID-3273: Prevent accomplice framing scenario

- src/meta_voting/meta_vote.rs
- src/meta_voting/meta_vote_counts.rs
- src/parsec.rs
This PR is trying to address the issue that meta_vote_counter will take extra counts in and exceeding the number of voters.
> fix/parsec: avoid count exceeding

- src/dev_utils/network.rs
- src/dev_utils/peer.rs
Pull clippy fix from Adam PR #232
> chore/all: address new clippy lints

- benches/bench.rs
- dot_gen/src/main.rs
- input_graphs/dev_utils_record_tests_smoke_other_peer_names/annie.dot
- src/dev_utils/dot_parser.rs
- src/dev_utils/schedule.rs
- src/dump_graph.rs
- src/gossip/event.rs
The first commit handle gracefully peers with same initial: Compute how long the short name needs to be to avoid any collision with given peers and use it for all peers. (This scheme does not modify existing test cases that only use peer with names from NAMES.)
The second commit extend our benchmark generating code to handle any number of peers. Add a 48 peers benchmark for 8 events only as 16 is still a bit slow.
> Benchmark with 48 peers: robust short peer name

- src/parsec.rs
is_interesting_payload showed high in flame graph for 1024 events.
Remove inefficiencies:
- Compute num_peers_that_did_vote only when needed.
- Process slow iteration/filter over BtreeMap only once for all the
peer in num_creators_of_ancestors_carrying_payload
Test:
time cargo bench --features=testing -- --baseline master
a_node4_opaque_evt1024 - bench_section_size_evt1024_interleave
time:   [324.09 ms 325.12 ms 325.44 ms]
change: [-9.2656% -6.9987% -5.4286%] (p = 0.02 < 0.05)
Change within noise threshold.
a_node8_opaque_evt1024 - bench_section_size_evt1024_interleave
time:   [1.0105 s 1.0111 s 1.0115 s]
change: [-22.335% -22.149% -21.935%] (p = 0.02 < 0.05)
Performance has improved.
a_node16_opaque_evt1024 - bench_section_size_evt1024_interleave
time:   [1.6307 s 1.6319 s 1.6348 s] …
> perf/parsec: 70% speed up in is_interesting_payload

- src/parsec.rs
Within the current test of concensus_with_fork, Carol and Bob will accuse Alice of fork at two different events.
We are supposed to accuse fork only at the root event (which means only one event_hash).
Also, we need to consider in the scenario of 
```
A0 --- A1_0 --- A2_0
\
\-- A1_1 --- A2_1
\
\-- A2_2
```
fork accusations are only casted against A0 and A1_1
and in the scenario of 
```
A0 --- A1_0 --- A2_0
\
\-- A1_1 --- A2_1
\
\-- A1_2
```
fork accusation is only casted against A0
And this PR is to achieve this.
> MAID-3285 fix/parsec: avoid accusing Fork duplicatedly

- src/dev_utils/dot_parser.rs
- src/functional_tests.rs
- src/gossip/cause.rs
- src/gossip/content.rs
- src/gossip/event.rs
- src/parsec.rs
WIP, because it depends on #279 .
> MAID-3084: Add test for invalid other parent

- src/parsec.rs
We will add a new kind of event to add at the end with DkgMessages.
Clarify how we are doing it with our existing events.
> refactor/parsec: simplify adding accusations and sync events.

- tests/integration_tests.rs
Closes #333 
Also use consensus mode single as routing does.
> test/parsec: minimally cover add/remove/opaque after DKG

- src/key_gen/tests.rs
Verify that the serialisation of a signature is the same regarless of
the set of signature share used.
This will be really important in routing to ensure duplicate messages
are filtered out even if the signature accumulating nodes get different
shares first.
Test:
Run new test + clippy.
> test/key_gen: serialise signatures the same with any share used
